server:
  port: 8082
spring:
  application:
    name: docker-redis-project
  datasource:
    url: jdbc:mysql://mysql:3306/testdb
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379